### ISSUE TITLE
Planned changes

### ISSUE THREAD

**Issue by kiwichrisbt** [kiwichrisbt/ReviewManager#2]
Next tasks
=======

- [x] update all admin .tpl 
- [x] get admin working
- [x] get FE working
- [x] fully test import & swapping to ReviewManager
- [x] remove CGExtensions dependency - could use CMSMSExt - but it wasn't available when I started. I was just going to get rid of any dependencies - especially any that I didn't have control over. I had started pushing any CGExtension methods into lib/class.utils.php
- [x] remove CGSimpleSmarty dependency - same as above with goal of removing dependcies
- [x] get working with PHP 8+

Wishlist of functionality to add
====================
- [x] can add reviews directly into CMS Admin
- [x] can edit created date in CMS Admin
- [x] can have image field
- [x] change review notification email to a comma separated list - not a User Group

**Comment by magalh** [comment]
updated tasklist checkmarks
